## Base de datos en Python

#### Recursos

sqlite3 https://docs.python.org/3/library/sqlite3.html

MySQL https://stackoverflow.com/questions/372885/how-do-i-connect-to-a-mysql-database-in-python

PostgresSQL https://wiki.postgresql.org/wiki/Using_psycopg2_with_PostgreSQL

Oracle https://stackoverflow.com/questions/49030388/how-to-connect-to-oracle-12c-database-using-cx-oracle

SQL Server https://stackoverflow.com/questions/33725862/connecting-to-microsoft-sql-server-using-python

### Ejercicio 1

Conectarse a una base de datos sqlite y extraer todos los clientes

In [2]:
import sqlite3

conn = sqlite3.connect("data/chinook.db")

cur = conn.cursor()

cur.execute("SELECT * FROM customers")

rows = cur.fetchall()

print(rows)

for row in rows:
    print(row[7])

[(1, 'Luís', 'Gonçalves', 'Embraer - Empresa Brasileira de Aeronáutica S.A.', 'Av. Brigadeiro Faria Lima, 2170', 'São José dos Campos', 'SP', 'Brazil', '12227-000', '+55 (12) 3923-5555', '+55 (12) 3923-5566', 'luisg@embraer.com.br', 3), (2, 'Leonie', 'Köhler', None, 'Theodor-Heuss-Straße 34', 'Stuttgart', None, 'Germany', '70174', '+49 0711 2842222', None, 'leonekohler@surfeu.de', 5), (3, 'François', 'Tremblay', None, '1498 rue Bélanger', 'Montréal', 'QC', 'Canada', 'H2G 1A7', '+1 (514) 721-4711', None, 'ftremblay@gmail.com', 3), (4, 'Bjørn', 'Hansen', None, 'Ullevålsveien 14', 'Oslo', None, 'Norway', '0171', '+47 22 44 22 22', None, 'bjorn.hansen@yahoo.no', 4), (5, 'František', 'Wichterlová', 'JetBrains s.r.o.', 'Klanova 9/506', 'Prague', None, 'Czech Republic', '14700', '+420 2 4172 5555', '+420 2 4172 5555', 'frantisekw@jetbrains.com', 4), (6, 'Helena', 'Holý', None, 'Rilská 3174/6', 'Prague', None, 'Czech Republic', '14300', '+420 2 4177 0449', None, 'hholy@gmail.com', 5), (7, 'Astrid', 'Gruber', None, 'Rotenturmstraße 4, 1010 Innere Stadt', 'Vienne', None, 'Austria', '1010', '+43 01 5134505', None, 'astrid.gruber@apple.at', 5), (8, 'Daan', 'Peeters', None, 'Grétrystraat 63', 'Brussels', None, 'Belgium', '1000', '+32 02 219 03 03', None, 'daan_peeters@apple.be', 4), (9, 'Kara', 'Nielsen', None, 'Sønder Boulevard 51', 'Copenhagen', None, 'Denmark', '1720', '+453 3331 9991', None, 'kara.nielsen@jubii.dk', 4), (10, 'Eduardo', 'Martins', 'Woodstock Discos', 'Rua Dr. Falcão Filho, 155', 'São Paulo', 'SP', 'Brazil', '01007-010', '+55 (11) 3033-5446', '+55 (11) 3033-4564', 'eduardo@woodstock.com.br', 4), (11, 'Alexandre', 'Rocha', 'Banco do Brasil S.A.', 'Av. Paulista, 2022', 'São Paulo', 'SP', 'Brazil', '01310-200', '+55 (11) 3055-3278', '+55 (11) 3055-8131', 'alero@uol.com.br', 5), (12, 'Roberto', 'Almeida', 'Riotur', 'Praça Pio X, 119', 'Rio de Janeiro', 'RJ', 'Brazil', '20040-020', '+55 (21) 2271-7000', '+55 (21) 2271-7070', 'roberto.almeida@riotur.gov.br', 3), (13, 'Fernanda', 'Ramos', None, 'Qe 7 Bloco G', 'Brasília', 'DF', 'Brazil', '71020-677', '+55 (61) 3363-5547', '+55 (61) 3363-7855', 'fernadaramos4@uol.com.br', 4), (14, 'Mark', 'Philips', 'Telus', '8210 111 ST NW', 'Edmonton', 'AB', 'Canada', 'T6G 2C7', '+1 (780) 434-4554', '+1 (780) 434-5565', 'mphilips12@shaw.ca', 5), (15, 'Jennifer', 'Peterson', 'Rogers Canada', '700 W Pender Street', 'Vancouver', 'BC', 'Canada', 'V6C 1G8', '+1 (604) 688-2255', '+1 (604) 688-8756', 'jenniferp@rogers.ca', 3), (16, 'Frank', 'Harris', 'Google Inc.', '1600 Amphitheatre Parkway', 'Mountain View', 'CA', 'USA', '94043-1351', '+1 (650) 253-0000', '+1 (650) 253-0000', 'fharris@google.com', 4), (17, 'Jack', 'Smith', 'Microsoft Corporation', '1 Microsoft Way', 'Redmond', 'WA', 'USA', '98052-8300', '+1 (425) 882-8080', '+1 (425) 882-8081', 'jacksmith@microsoft.com', 5), (18, 'Michelle', 'Brooks', None, '627 Broadway', 'New York', 'NY', 'USA', '10012-2612', '+1 (212) 221-3546', '+1 (212) 221-4679', 'michelleb@aol.com', 3), (19, 'Tim', 'Goyer', 'Apple Inc.', '1 Infinite Loop', 'Cupertino', 'CA', 'USA', '95014', '+1 (408) 996-1010', '+1 (408) 996-1011', 'tgoyer@apple.com', 3), (20, 'Dan', 'Miller', None, '541 Del Medio Avenue', 'Mountain View', 'CA', 'USA', '94040-111', '+1 (650) 644-3358', None, 'dmiller@comcast.com', 4), (21, 'Kathy', 'Chase', None, '801 W 4th Street', 'Reno', 'NV', 'USA', '89503', '+1 (775) 223-7665', None, 'kachase@hotmail.com', 5), (22, 'Heather', 'Leacock', None, '120 S Orange Ave', 'Orlando', 'FL', 'USA', '32801', '+1 (407) 999-7788', None, 'hleacock@gmail.com', 4), (23, 'John', 'Gordon', None, '69 Salem Street', 'Boston', 'MA', 'USA', '2113', '+1 (617) 522-1333', None, 'johngordon22@yahoo.com', 4), (24, 'Frank', 'Ralston', None, '162 E Superior Street', 'Chicago', 'IL', 'USA', '60611', '+1 (312) 332-3232', None, 'fralston@gmail.com', 3), (25, 'Victor', 'Stevens', None, '319 N. Frances Street', 'Madison', 'WI', 'USA', '53703', '+1 (608) 257-0597', None, 'vstevens@yahoo.com', 5), (26, 'Richard', 'Cunningham', None, '2211 W Berry Street', 'Fort Worth', 'TX', 'USA', '76110', '+1 (817) 924-7272', None, 'ricunningham@hotmail.com', 4), (27, 'Patrick', 'Gray', None, '1033 N Park Ave', 'Tucson', 'AZ', 'USA', '85719', '+1 (520) 622-4200', None, 'patrick.gray@aol.com', 4), (28, 'Julia', 'Barnett', None, '302 S 700 E', 'Salt Lake City', 'UT', 'USA', '84102', '+1 (801) 531-7272', None, 'jubarnett@gmail.com', 5), (29, 'Robert', 'Brown', None, '796 Dundas Street West', 'Toronto', 'ON', 'Canada', 'M6J 1V1', '+1 (416) 363-8888', None, 'robbrown@shaw.ca', 3), (30, 'Edward', 'Francis', None, '230 Elgin Street', 'Ottawa', 'ON', 'Canada', 'K2P 1L7', '+1 (613) 234-3322', None, 'edfrancis@yachoo.ca', 3), (31, 'Martha', 'Silk', None, '194A Chain Lake Drive', 'Halifax', 'NS', 'Canada', 'B3S 1C5', '+1 (902) 450-0450', None, 'marthasilk@gmail.com', 5), (32, 'Aaron', 'Mitchell', None, '696 Osborne Street', 'Winnipeg', 'MB', 'Canada', 'R3L 2B9', '+1 (204) 452-6452', None, 'aaronmitchell@yahoo.ca', 4), (33, 'Ellie', 'Sullivan', None, '5112 48 Street', 'Yellowknife', 'NT', 'Canada', 'X1A 1N6', '+1 (867) 920-2233', None, 'ellie.sullivan@shaw.ca', 3), (34, 'João', 'Fernandes', None, 'Rua da Assunção 53', 'Lisbon', None, 'Portugal', None, '+351 (213) 466-111', None, 'jfernandes@yahoo.pt', 4), (35, 'Madalena', 'Sampaio', None, 'Rua dos Campeões Europeus de Viena, 4350', 'Porto', None, 'Portugal', None, '+351 (225) 022-448', None, 'masampaio@sapo.pt', 4), (36, 'Hannah', 'Schneider', None, 'Tauentzienstraße 8', 'Berlin', None, 'Germany', '10789', '+49 030 26550280', None, 'hannah.schneider@yahoo.de', 5), (37, 'Fynn', 'Zimmermann', None, 'Berger Straße 10', 'Frankfurt', None, 'Germany', '60316', '+49 069 40598889', None, 'fzimmermann@yahoo.de', 3), (38, 'Niklas', 'Schröder', None, 'Barbarossastraße 19', 'Berlin', None, 'Germany', '10779', '+49 030 2141444', None, 'nschroder@surfeu.de', 3), (39, 'Camille', 'Bernard', None, '4, Rue Milton', 'Paris', None, 'France', '75009', '+33 01 49 70 65 65', None, 'camille.bernard@yahoo.fr', 4), (40, 'Dominique', 'Lefebvre', None, '8, Rue Hanovre', 'Paris', None, 'France', '75002', '+33 01 47 42 71 71', None, 'dominiquelefebvre@gmail.com', 4), (41, 'Marc', 'Dubois', None, '11, Place Bellecour', 'Lyon', None, 'France', '69002', '+33 04 78 30 30 30', None, 'marc.dubois@hotmail.com', 5), (42, 'Wyatt', 'Girard', None, '9, Place Louis Barthou', 'Bordeaux', None, 'France', '33000', '+33 05 56 96 96 96', None, 'wyatt.girard@yahoo.fr', 3), (43, 'Isabelle', 'Mercier', None, '68, Rue Jouvence', 'Dijon', None, 'France', '21000', '+33 03 80 73 66 99', None, 'isabelle_mercier@apple.fr', 3), (44, 'Terhi', 'Hämäläinen', None, 'Porthaninkatu 9', 'Helsinki', None, 'Finland', '00530', '+358 09 870 2000', None, 'terhi.hamalainen@apple.fi', 3), (45, 'Ladislav', 'Kovács', None, 'Erzsébet krt. 58.', 'Budapest', None, 'Hungary', 'H-1073', None, None, 'ladislav_kovacs@apple.hu', 3), (46, 'Hugh', "O'Reilly", None, '3 Chatham Street', 'Dublin', 'Dublin', 'Ireland', None, '+353 01 6792424', None, 'hughoreilly@apple.ie', 3), (47, 'Lucas', 'Mancini', None, 'Via Degli Scipioni, 43', 'Rome', 'RM', 'Italy', '00192', '+39 06 39733434', None, 'lucas.mancini@yahoo.it', 5), (48, 'Johannes', 'Van der Berg', None, 'Lijnbaansgracht 120bg', 'Amsterdam', 'VV', 'Netherlands', '1016', '+31 020 6223130', None, 'johavanderberg@yahoo.nl', 5), (49, 'Stanisław', 'Wójcik', None, 'Ordynacka 10', 'Warsaw', None, 'Poland', '00-358', '+48 22 828 37 39', None, 'stanisław.wójcik@wp.pl', 4), (50, 'Enrique', 'Muñoz', None, 'C/ San Bernardo 85', 'Madrid', None, 'Spain', '28015', '+34 914 454 454', None, 'enrique_munoz@yahoo.es', 5), (51, 'Joakim', 'Johansson', None, 'Celsiusg. 9', 'Stockholm', None, 'Sweden', '11230', '+46 08-651 52 52', None, 'joakim.johansson@yahoo.se', 5), (52, 'Emma', 'Jones', None, '202 Hoxton Street', 'London', None, 'United Kingdom', 'N1 5LH', '+44 020 7707 0707', None, 'emma_jones@hotmail.com', 3), (53, 'Phil', 'Hughes', None, '113 Lupus St', 'London', None, 'United Kingdom', 'SW1V 3EN', '+44 020 7976 5722', None, 'phil.hughes@gmail.com', 3), (54, 'Steve', 'Murray', None, '110 Raeburn Pl', 'Edinburgh ', None, 'United Kingdom', 'EH4 1HH', '+44 0131 315 3300', None, 'steve.murray@yahoo.uk', 5), (55, 'Mark', 'Taylor', None, '421 Bourke Street', 'Sidney', 'NSW', 'Australia', '2010', '+61 (02) 9332 3633', None, 'mark.taylor@yahoo.au', 4), (56, 'Diego', 'Gutiérrez', None, '307 Macacha Güemes', 'Buenos Aires', None, 'Argentina', '1106', '+54 (0)11 4311 4333', None, 'diego.gutierrez@yahoo.ar', 4), (57, 'Luis', 'Rojas', None, 'Calle Lira, 198', 'Santiago', None, 'Chile', None, '+56 (0)2 635 4444', None, 'luisrojas@yahoo.cl', 5), (58, 'Manoj', 'Pareek', None, '12,Community Centre', 'Delhi', None, 'India', '110017', '+91 0124 39883988', None, 'manoj.pareek@rediff.com', 3), (59, 'Puja', 'Srivastava', None, '3,Raj Bhavan Road', 'Bangalore', None, 'India', '560001', '+91 080 22289999', None, 'puja_srivastava@yahoo.in', 3)]
Brazil
Germany
Canada
Norway
Czech Republic
Czech Republic
Austria
Belgium
Denmark
Brazil
Brazil
Brazil
Brazil
Canada
Canada
USA
USA
USA
USA
USA
USA
USA
USA
USA
USA
USA
USA
USA
Canada
Canada
Canada
Canada
Canada
Portugal
Portugal
Germany
Germany
Germany
France
France
France
France
France
Finland
Hungary
Ireland
Italy
Netherlands
Poland
Spain
Sweden
United Kingdom
United Kingdom
United Kingdom
Australia
Argentina
Chile
India
India

### Ejercicio 2

Conectarse a la base de datos y extraer todos los clientes con pandas

In [2]:
import pandas as pd

pd.read_sql("SELECT * FROM customers", conn)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
6,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
7,8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
8,9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
17,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
19,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
20,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
21,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
22,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
23,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
24,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
25,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
26,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
27,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
28,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
29,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
30,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
31,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
32,33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
33,34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
34,35,Madalena,Sampaio,None,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
35,36,Hannah,Schneider,None,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
36,37,Fynn,Zimmermann,None,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
37,38,Niklas,Schröder,None,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
38,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
41,42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
42,43,Isabelle,Mercier,None,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
43,44,Terhi,Hämäläinen,None,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
44,45,Ladislav,Kovács,None,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
45,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
46,47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
47,48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
48,49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
49,50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
50,51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
51,52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
52,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
53,54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
55,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
57,58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
58,59,Puja,Srivastava,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3

### Ejercicio 3

Extraer artistas y sus albums (con sql y con pandas)

In [3]:
pd.read_sql("SELECT Name, Title FROM artists ar JOIN albums al ON ar.ArtistId = al.ArtistId", conn)

,Name,Title
0,AC/DC,For Those About To Rock We Salute You
1,Accept,Balls to the Wall
2,Accept,Restless and Wild
3,AC/DC,Let There Be Rock
4,Aerosmith,Big Ones
5,Alanis Morissette,Jagged Little Pill
6,Alice In Chains,Facelift
7,Antônio Carlos Jobim,Warner 25 Anos
8,Apocalyptica,Plays Metallica By Four Cellos
9,Audioslave,Audioslave
10,Audioslave,Out Of Exile
11,BackBeat,BackBeat Soundtrack
12,Billy Cobham,The Best Of Billy Cobham
13,Black Label Society,Alcohol Fueled Brewtality Live! [Disc 1]
14,Black Label Society,Alcohol Fueled Brewtality Live! [Disc 2]
15,Black Sabbath,Black Sabbath
16,Black Sabbath,Black Sabbath Vol. 4 (Remaster)
17,Body Count,Body Count
18,Bruce Dickinson,Chemical Wedding
19,Buddy Guy,The Best Of Buddy Guy - The Millenium Collection
20,Caetano Veloso,Prenda Minha
21,Caetano Veloso,Sozinho Remix Ao Vivo
22,Chico Buarque,Minha Historia
23,Chico Science & Nação Zumbi,Afrociberdelia
24,Chico Science & Nação Zumbi,Da Lama Ao Caos
25,Cidade Negra,Acústico MTV [Live]
26,Cidade Negra,Cidade Negra - Hits
27,Cláudio Zoli,Na Pista
28,Various Artists,Axé Bahia 2001
29,Led Zeppelin,BBC Sessions [Disc 1] [Live]
...,...,...
317,Christopher O'Riley,SCRIABIN: Vers la flamme
318,Fretwork,Armada: Music from the Courts of England and S...
319,Berliner Philharmoniker & Herbert Von Karajan,Mozart: Symphonies Nos. 40 & 41
320,Amy Winehouse,Back to Black
321,Amy Winehouse,Frank
322,Calexico,Carried to Dust (Bonus Track Version)
323,Otto Klemperer & Philharmonia Orchestra,Beethoven: Symphony No. 6 'Pastoral' Etc.
324,Yehudi Menuhin,Bartok: Violin & Viola Concertos
325,Philharmonia Orchestra & Sir Neville Marriner,Mendelssohn: A Midsummer Night's Dream
326,"Academy of St. Martin in the Fields, Sir Nevil...",Bach: Orchestral Suites Nos. 1 - 4
327,Les Arts Florissants & William Christie,"Charpentier: Divertissements, Airs & Concerts"
328,The 12 Cellists of The Berlin Philharmonic,South American Getaway
329,Adrian Leaper & Doreen de Feis,Górecki: Symphony No. 3
330,"Roger Norrington, London Classical Players",Purcell: The Fairy Queen
331,Charles Dutoit & L'Orchestre Symphonique de Mo...,The Ultimate Relexation Album
332,"Equale Brass Ensemble, John Eliot Gardiner & M...",Purcell: Music for the Queen Mary
333,Kent Nagano and Orchestre de l'Opéra de Lyon,Weill: The Seven Deadly Sins
334,Julian Bream,"J.S. Bach: Chaconne, Suite in E Minor, Partita..."
335,Berliner Philharmoniker & Herbert Von Karajan,Prokofiev: Symphony No.5 & Stravinksy: Le Sacr...
336,Martin Roscoe,"Szymanowski: Piano Works, Vol. 1"
337,Göteborgs Symfoniker & Neeme Järvi,Nielsen: The Six Symphonies
338,Itzhak Perlman,Great Recordings of the Century: Paganini's 24...
339,Michele Campanella,Liszt - 12 Études D'Execution Transcendante
340,Gerald Moore,Great Recordings of the Century - Shubert: Sch...
341,"Mela Tenenbaum, Pro Musica Prague & Richard Kapp","Locatelli: Concertos for Violin, Strings and C..."
342,Eugene Ormandy,Respighi:Pines of Rome
343,Emerson String Quartet,Schubert: The Late String Quartets & String Qu...
344,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...",Monteverdi: L'Orfeo
345,Nash Ensemble,Mozart: Chamber Music
346,Philip Glass Ensemble,Koyaanisqatsi (Soundtrack from the Motion Pict...

In [4]:
df1 = pd.read_sql("SELECT * FROM artists", conn)
df2 = pd.read_sql("SELECT * FROM albums", conn)
df3 = pd.merge(df1, df2, on="ArtistId")
df3

,ArtistId,Name,AlbumId,Title
0,1,AC/DC,1,For Those About To Rock We Salute You
1,1,AC/DC,4,Let There Be Rock
2,2,Accept,2,Balls to the Wall
3,2,Accept,3,Restless and Wild
4,3,Aerosmith,5,Big Ones
5,4,Alanis Morissette,6,Jagged Little Pill
6,5,Alice In Chains,7,Facelift
7,6,Antônio Carlos Jobim,8,Warner 25 Anos
8,6,Antônio Carlos Jobim,34,Chill: Brazil (Disc 2)
9,7,Apocalyptica,9,Plays Metallica By Four Cellos
10,8,Audioslave,10,Audioslave
11,8,Audioslave,11,Out Of Exile
12,8,Audioslave,271,Revelations
13,9,BackBeat,12,BackBeat Soundtrack
14,10,Billy Cobham,13,The Best Of Billy Cobham
15,11,Black Label Society,14,Alcohol Fueled Brewtality Live! [Disc 1]
16,11,Black Label Society,15,Alcohol Fueled Brewtality Live! [Disc 2]
17,12,Black Sabbath,16,Black Sabbath
18,12,Black Sabbath,17,Black Sabbath Vol. 4 (Remaster)
19,13,Body Count,18,Body Count
20,14,Bruce Dickinson,19,Chemical Wedding
21,15,Buddy Guy,20,The Best Of Buddy Guy - The Millenium Collection
22,16,Caetano Veloso,21,Prenda Minha
23,16,Caetano Veloso,22,Sozinho Remix Ao Vivo
24,17,Chico Buarque,23,Minha Historia
25,18,Chico Science & Nação Zumbi,24,Afrociberdelia
26,18,Chico Science & Nação Zumbi,25,Da Lama Ao Caos
27,19,Cidade Negra,26,Acústico MTV [Live]
28,19,Cidade Negra,27,Cidade Negra - Hits
29,20,Cláudio Zoli,28,Na Pista
...,...,...,...,...
317,248,Berliner Philharmoniker & Herbert Von Karajan,320,Mozart: Symphonies Nos. 40 & 41
318,248,Berliner Philharmoniker & Herbert Von Karajan,336,Prokofiev: Symphony No.5 & Stravinksy: Le Sacr...
319,249,"Sir Georg Solti, Sumi Jo & Wiener Philharmoniker",317,Mozart Gala: Famous Arias
320,250,Christopher O'Riley,318,SCRIABIN: Vers la flamme
321,251,Fretwork,319,Armada: Music from the Courts of England and S...
322,252,Amy Winehouse,321,Back to Black
323,252,Amy Winehouse,322,Frank
324,253,Calexico,323,Carried to Dust (Bonus Track Version)
325,254,Otto Klemperer & Philharmonia Orchestra,324,Beethoven: Symphony No. 6 'Pastoral' Etc.
326,255,Yehudi Menuhin,325,Bartok: Violin & Viola Concertos
327,256,Philharmonia Orchestra & Sir Neville Marriner,326,Mendelssohn: A Midsummer Night's Dream
328,257,"Academy of St. Martin in the Fields, Sir Nevil...",327,Bach: Orchestral Suites Nos. 1 - 4
329,258,Les Arts Florissants & William Christie,328,"Charpentier: Divertissements, Airs & Concerts"
330,259,The 12 Cellists of The Berlin Philharmonic,329,South American Getaway
331,260,Adrian Leaper & Doreen de Feis,330,Górecki: Symphony No. 3
332,261,"Roger Norrington, London Classical Players",331,Purcell: The Fairy Queen
333,262,Charles Dutoit & L'Orchestre Symphonique de Mo...,332,The Ultimate Relexation Album
334,263,"Equale Brass Ensemble, John Eliot Gardiner & M...",333,Purcell: Music for the Queen Mary
335,264,Kent Nagano and Orchestre de l'Opéra de Lyon,334,Weill: The Seven Deadly Sins
336,265,Julian Bream,335,"J.S. Bach: Chaconne, Suite in E Minor, Partita..."
337,266,Martin Roscoe,337,"Szymanowski: Piano Works, Vol. 1"
338,267,Göteborgs Symfoniker & Neeme Järvi,338,Nielsen: The Six Symphonies
339,268,Itzhak Perlman,339,Great Recordings of the Century: Paganini's 24...
340,269,Michele Campanella,340,Liszt - 12 Études D'Execution Transcendante
341,270,Gerald Moore,341,Great Recordings of the Century - Shubert: Sch...
342,271,"Mela Tenenbaum, Pro Musica Prague & Richard Kapp",342,"Locatelli: Concertos for Violin, Strings and C..."
343,272,Emerson String Quartet,344,Schubert: The Late String Quartets & String Qu...
344,273,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...",345,Monteverdi: L'Orfeo
345,274,Nash Ensemble,346,Mozart: Chamber Music
346,275,Philip Glass Ensemble,347,Koyaanisqatsi (Soundtrack from the Motion Pict...

### Ejercicio 4

Escribir una tabla con albumes y artistas desde un dataframe

In [5]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /home/caracena/Documents/Projects/venv3.6/lib/python3.6/site-packages (1.2.15)

In [6]:
from sqlalchemy import create_engine
sql_engine = create_engine('sqlite:///data/test.db', echo=False)
connection = sql_engine.raw_connection()
df3.to_sql('artists_albums', connection, index=False, if_exists='append')

In [7]:
conn1 = sqlite3.connect("data/test.db")
pd.read_sql("SELECT * FROM artists_albums", conn1)

,ArtistId,Name,AlbumId,Title
0,1,AC/DC,1,For Those About To Rock We Salute You
1,1,AC/DC,4,Let There Be Rock
2,2,Accept,2,Balls to the Wall
3,2,Accept,3,Restless and Wild
4,3,Aerosmith,5,Big Ones
5,4,Alanis Morissette,6,Jagged Little Pill
6,5,Alice In Chains,7,Facelift
7,6,Antônio Carlos Jobim,8,Warner 25 Anos
8,6,Antônio Carlos Jobim,34,Chill: Brazil (Disc 2)
9,7,Apocalyptica,9,Plays Metallica By Four Cellos
10,8,Audioslave,10,Audioslave
11,8,Audioslave,11,Out Of Exile
12,8,Audioslave,271,Revelations
13,9,BackBeat,12,BackBeat Soundtrack
14,10,Billy Cobham,13,The Best Of Billy Cobham
15,11,Black Label Society,14,Alcohol Fueled Brewtality Live! [Disc 1]
16,11,Black Label Society,15,Alcohol Fueled Brewtality Live! [Disc 2]
17,12,Black Sabbath,16,Black Sabbath
18,12,Black Sabbath,17,Black Sabbath Vol. 4 (Remaster)
19,13,Body Count,18,Body Count
20,14,Bruce Dickinson,19,Chemical Wedding
21,15,Buddy Guy,20,The Best Of Buddy Guy - The Millenium Collection
22,16,Caetano Veloso,21,Prenda Minha
23,16,Caetano Veloso,22,Sozinho Remix Ao Vivo
24,17,Chico Buarque,23,Minha Historia
25,18,Chico Science & Nação Zumbi,24,Afrociberdelia
26,18,Chico Science & Nação Zumbi,25,Da Lama Ao Caos
27,19,Cidade Negra,26,Acústico MTV [Live]
28,19,Cidade Negra,27,Cidade Negra - Hits
29,20,Cláudio Zoli,28,Na Pista
...,...,...,...,...
1011,248,Berliner Philharmoniker & Herbert Von Karajan,320,Mozart: Symphonies Nos. 40 & 41
1012,248,Berliner Philharmoniker & Herbert Von Karajan,336,Prokofiev: Symphony No.5 & Stravinksy: Le Sacr...
1013,249,"Sir Georg Solti, Sumi Jo & Wiener Philharmoniker",317,Mozart Gala: Famous Arias
1014,250,Christopher O'Riley,318,SCRIABIN: Vers la flamme
1015,251,Fretwork,319,Armada: Music from the Courts of England and S...
1016,252,Amy Winehouse,321,Back to Black
1017,252,Amy Winehouse,322,Frank
1018,253,Calexico,323,Carried to Dust (Bonus Track Version)
1019,254,Otto Klemperer & Philharmonia Orchestra,324,Beethoven: Symphony No. 6 'Pastoral' Etc.
1020,255,Yehudi Menuhin,325,Bartok: Violin & Viola Concertos
1021,256,Philharmonia Orchestra & Sir Neville Marriner,326,Mendelssohn: A Midsummer Night's Dream
1022,257,"Academy of St. Martin in the Fields, Sir Nevil...",327,Bach: Orchestral Suites Nos. 1 - 4
1023,258,Les Arts Florissants & William Christie,328,"Charpentier: Divertissements, Airs & Concerts"
1024,259,The 12 Cellists of The Berlin Philharmonic,329,South American Getaway
1025,260,Adrian Leaper & Doreen de Feis,330,Górecki: Symphony No. 3
1026,261,"Roger Norrington, London Classical Players",331,Purcell: The Fairy Queen
1027,262,Charles Dutoit & L'Orchestre Symphonique de Mo...,332,The Ultimate Relexation Album
1028,263,"Equale Brass Ensemble, John Eliot Gardiner & M...",333,Purcell: Music for the Queen Mary
1029,264,Kent Nagano and Orchestre de l'Opéra de Lyon,334,Weill: The Seven Deadly Sins
1030,265,Julian Bream,335,"J.S. Bach: Chaconne, Suite in E Minor, Partita..."
1031,266,Martin Roscoe,337,"Szymanowski: Piano Works, Vol. 1"
1032,267,Göteborgs Symfoniker & Neeme Järvi,338,Nielsen: The Six Symphonies
1033,268,Itzhak Perlman,339,Great Recordings of the Century: Paganini's 24...
1034,269,Michele Campanella,340,Liszt - 12 Études D'Execution Transcendante
1035,270,Gerald Moore,341,Great Recordings of the Century - Shubert: Sch...
1036,271,"Mela Tenenbaum, Pro Musica Prague & Richard Kapp",342,"Locatelli: Concertos for Violin, Strings and C..."
1037,272,Emerson String Quartet,344,Schubert: The Late String Quartets & String Qu...
1038,273,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...",345,Monteverdi: L'Orfeo
1039,274,Nash Ensemble,346,Mozart: Chamber Music
1040,275,Philip Glass Ensemble,347,Koyaanisqatsi (Soundtrack from the Motion Pict...

### Ejercicio 5

Realizar consultas en pandas sin usar SQL

In [8]:
## SELECT FirstName FROM Customers;

customers = pd.read_sql("SELECT * FROM customers", conn)
customers['FirstName']

0          Luís
1        Leonie
2      François
3         Bjørn
4     František
5        Helena
6        Astrid
7          Daan
8          Kara
9       Eduardo
10    Alexandre
11      Roberto
12     Fernanda
13         Mark
14     Jennifer
15        Frank
16         Jack
17     Michelle
18          Tim
19          Dan
20        Kathy
21      Heather
22         John
23        Frank
24       Victor
25      Richard
26      Patrick
27        Julia
28       Robert
29       Edward
30       Martha
31        Aaron
32        Ellie
33         João
34     Madalena
35       Hannah
36         Fynn
37       Niklas
38      Camille
39    Dominique
40         Marc
41        Wyatt
42     Isabelle
43        Terhi
44     Ladislav
45         Hugh
46        Lucas
47     Johannes
48    Stanisław
49      Enrique
50       Joakim
51         Emma
52         Phil
53        Steve
54         Mark
55        Diego
56         Luis
57        Manoj
58         Puja
Name: FirstName, dtype: object

In [9]:
## SELECT DISTINCT Country FROM Customers;

customers['Country'].unique()

array(['Brazil', 'Germany', 'Canada', 'Norway', 'Czech Republic',
       'Austria', 'Belgium', 'Denmark', 'USA', 'Portugal', 'France',
       'Finland', 'Hungary', 'Ireland', 'Italy', 'Netherlands', 'Poland',
       'Spain', 'Sweden', 'United Kingdom', 'Australia', 'Argentina',
       'Chile', 'India'], dtype=object)

In [10]:
customers['Country'].value_counts()

USA               13
Canada             8
Brazil             5
France             5
Germany            4
United Kingdom     3
Portugal           2
Czech Republic     2
India              2
Denmark            1
Australia          1
Austria            1
Poland             1
Italy              1
Chile              1
Netherlands        1
Hungary            1
Norway             1
Sweden             1
Belgium            1
Spain              1
Finland            1
Ireland            1
Argentina          1
Name: Country, dtype: int64

In [11]:
## SELECT DISTINCT City, Country FROM Customers;

customers[['Country', 'City']].drop_duplicates()

           Country                 City
0           Brazil  São José dos Campos
1          Germany            Stuttgart
2           Canada             Montréal
3           Norway                 Oslo
4   Czech Republic               Prague
6          Austria               Vienne
7          Belgium             Brussels
8          Denmark           Copenhagen
9           Brazil            São Paulo
11          Brazil       Rio de Janeiro
12          Brazil             Brasília
13          Canada             Edmonton
14          Canada            Vancouver
15             USA        Mountain View
16             USA              Redmond
17             USA             New York
18             USA            Cupertino
20             USA                 Reno
21             USA              Orlando
22             USA               Boston
23             USA              Chicago
24             USA              Madison
25             USA           Fort Worth
26             USA               Tucson
27             USA       Salt Lake City
28          Canada              Toronto
29          Canada               Ottawa
30          Canada              Halifax
31          Canada             Winnipeg
32          Canada          Yellowknife
33        Portugal               Lisbon
34        Portugal                Porto
35         Germany               Berlin
36         Germany            Frankfurt
38          France                Paris
40          France                 Lyon
41          France             Bordeaux
42          France                Dijon
43         Finland             Helsinki
44         Hungary             Budapest
45         Ireland               Dublin
46           Italy                 Rome
47     Netherlands            Amsterdam
48          Poland               Warsaw
49           Spain               Madrid
50          Sweden            Stockholm
51  United Kingdom               London
53  United Kingdom           Edinburgh
54       Australia               Sidney
55       Argentina         Buenos Aires
56           Chile             Santiago
57           India                Delhi
58           India            Bangalore

In [12]:
## SELECT * FROM Customers ORDER BY Country;

customers.sort_values('Country')

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
55,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
6,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
7,8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
32,33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
31,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
30,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
28,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
29,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
8,9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
43,44,Terhi,Hämäläinen,None,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
38,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
42,43,Isabelle,Mercier,None,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
41,42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
37,38,Niklas,Schröder,None,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
35,36,Hannah,Schneider,None,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
36,37,Fynn,Zimmermann,None,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
44,45,Ladislav,Kovács,None,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
58,59,Puja,Srivastava,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3
57,58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
45,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
46,47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
47,48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
48,49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
33,34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
34,35,Madalena,Sampaio,None,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
49,50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
50,51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
17,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
24,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
23,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
26,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
25,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
19,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
20,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
21,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
22,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
27,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
51,52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
52,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
53,54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5

In [13]:
## SELECT * FROM Customers ORDER BY Country DESC;

customers.sort_values('Country', ascending=False)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
53,54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
52,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
51,52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
21,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
23,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
22,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
26,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
20,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
19,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
17,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
24,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
25,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
27,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
50,51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
49,50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
33,34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
34,35,Madalena,Sampaio,None,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
48,49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
47,48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
46,47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
45,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
58,59,Puja,Srivastava,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3
57,58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
44,45,Ladislav,Kovács,None,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
35,36,Hannah,Schneider,None,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
36,37,Fynn,Zimmermann,None,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
37,38,Niklas,Schröder,None,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
42,43,Isabelle,Mercier,None,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
38,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
41,42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
43,44,Terhi,Hämäläinen,None,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
8,9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
5,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
29,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
32,33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
31,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
30,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
28,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
12,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
7,8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
6,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
55,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4

In [14]:
## SELECT FirstName, City, Country FROM Customers ORDER BY Country ASC, City DESC;

customers.sort_values(['Country', 'City'], ascending=[True, False])

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
55,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
6,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
7,8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
32,33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
31,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
28,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
29,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
30,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
8,9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
43,44,Terhi,Hämäläinen,None,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
38,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
42,43,Isabelle,Mercier,None,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
41,42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
36,37,Fynn,Zimmermann,None,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
35,36,Hannah,Schneider,None,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
37,38,Niklas,Schröder,None,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
44,45,Ladislav,Kovács,None,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
57,58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
58,59,Puja,Srivastava,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3
45,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
46,47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
47,48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
48,49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
34,35,Madalena,Sampaio,None,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
33,34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
49,50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
50,51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
26,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
27,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
20,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
21,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
17,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
19,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
24,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
25,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
23,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
22,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
51,52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
52,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
53,54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5

In [15]:
## SELECT * FROM Customers WHERE Country = 'Brazil';

customers[customers['Country'] == 'Brazil']

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4

In [16]:
## SELECT * FROM Customers WHERE Country = 'USA' AND City = 'Mountain View';

customers[(customers['Country'] == 'USA') & (customers['City'] == 'Mountain View')]

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
19,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4

In [17]:
## SELECT * FROM Customers WHERE Country = 'Chile' OR City = 'Buenos Aires';

customers[(customers['Country'] == 'Chile') | (customers['City'] == 'Buenos Aires')]

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
55,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5

In [18]:
## SELECT * FROM Customers WHERE Country IN ('Chile', 'Australia');

customers[customers['Country'].isin(['Chile', 'Australia'])]

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5

In [19]:
## SELECT * FROM Customers WHERE Country LIKE 'A%';

customers[customers['Country'].str.startswith('A')]

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
6,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
55,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4

In [20]:
## SELECT *, 1.19 * Total FROM 'invoices';

invoices = pd.read_sql("SELECT * FROM invoices", conn)
invoices['Total_new'] = invoices['Total'] * 1.19
invoices

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,Total_new
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,2.3562
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96,4.7124
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94,7.0686
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91,10.6029
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86,16.4934
5,6,37,2009-01-19 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,0.99,1.1781
6,7,38,2009-02-01 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98,2.3562
7,8,40,2009-02-01 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,1.98,2.3562
8,9,42,2009-02-02 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,3.96,4.7124
9,10,46,2009-02-03 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,5.94,7.0686
10,11,52,2009-02-06 00:00:00,202 Hoxton Street,London,None,United Kingdom,N1 5LH,8.91,10.6029
11,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,16.4934
12,13,16,2009-02-19 00:00:00,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,0.99,1.1781
13,14,17,2009-03-04 00:00:00,1 Microsoft Way,Redmond,WA,USA,98052-8300,1.98,2.3562
14,15,19,2009-03-04 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,1.98,2.3562
15,16,21,2009-03-05 00:00:00,801 W 4th Street,Reno,NV,USA,89503,3.96,4.7124
16,17,25,2009-03-06 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,5.94,7.0686
17,18,31,2009-03-09 00:00:00,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,8.91,10.6029
18,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86,16.4934
19,20,54,2009-03-22 00:00:00,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,0.99,1.1781
20,21,55,2009-04-04 00:00:00,421 Bourke Street,Sidney,NSW,Australia,2010,1.98,2.3562
21,22,57,2009-04-04 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,1.98,2.3562
22,23,59,2009-04-05 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,3.96,4.7124
23,24,4,2009-04-06 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,5.94,7.0686
24,25,10,2009-04-09 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,8.91,10.6029
25,26,19,2009-04-14 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,13.86,16.4934
26,27,33,2009-04-22 00:00:00,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,0.99,1.1781
27,28,34,2009-05-05 00:00:00,Rua da Assunção 53,Lisbon,None,Portugal,None,1.98,2.3562
28,29,36,2009-05-05 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98,2.3562
29,30,38,2009-05-06 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,3.96,4.7124
...,...,...,...,...,...,...,...,...,...,...
382,383,10,2013-08-12 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,13.86,16.4934
383,384,24,2013-08-20 00:00:00,162 E Superior Street,Chicago,IL,USA,60611,0.99,1.1781
384,385,25,2013-09-02 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,1.98,2.3562
385,386,27,2013-09-02 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,1.98,2.3562
386,387,29,2013-09-03 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,3.96,4.7124
387,388,33,2013-09-04 00:00:00,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,5.94,7.0686
388,389,39,2013-09-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,8.91,10.6029
389,390,48,2013-09-12 00:00:00,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,13.86,16.4934
390,391,3,2013-09-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,0.99,1.1781
391,392,4,2013-10-03 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,1.98,2.3562
392,393,6,2013-10-03 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,1.98,2.3562
393,394,8,2013-10-04 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,3.96,4.7124
394,395,12,2013-10-05 00:00:00,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,5.94,7.0686
395,396,18,2013-10-08 00:00:00,627 Broadway,New York,NY,USA,10012-2612,8.91,10.6029
396,397,27,2013-10-13 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,13.86,16.4934
397,398,41,2013-10-21 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,0.99,1.1781
398,399,42,2013-11-03 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,1.98,2.3562
399,400,44,2013-11-03 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,1.98,2.3562
400,401,46,2013-11-04 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,3.96,4.7124
401,402,50,2013-11-05 00:00:00,C/ San Bernardo 85,Madrid,None,Spain,28015,5.94,7.0686
402,403,56,2013-11-08 00:00:00,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,8.91,10.6029
403,404,6,2013-11-13 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,25.86,30.7734
404,405,20,2013-11-21 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,0.99,1.1781
405,406,21,2013-12-04 00:00:00,801 W 4th Street,Reno,NV,USA,89503,1.98,2.3562
406,407,23,2013-12-04 00:00:00,69 Salem Street,Boston,MA,USA,2113,1.98,2.3562
407,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96,4.7124
408,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94,7.0686
409,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91,10.6029
410,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86,16.4934
411,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99,2.3681

In [21]:
## SELECT min(Total) FROM Invoices;
invoices['Total'].min()

0.99

In [22]:
invoices.min()

InvoiceId                           1
CustomerId                          1
InvoiceDate       2009-01-01 00:00:00
BillingAddress        1 Infinite Loop
BillingCity                 Amsterdam
BillingCountry              Argentina
Total                            0.99
Total_new                      1.1781
dtype: object

In [23]:
## SELECT max(Total) FROM Invoices;
invoices['Total'].max()

25.86

In [24]:
invoices['Total'].describe()[['mean', 'count']]

mean       5.651942
count    412.000000
Name: Total, dtype: float64

In [25]:
## SELECT sum(Total) FROM Invoices WHERE BillingCountry = 'Germany';
invoices[invoices['BillingCountry'] == 'Germany']['Total'].sum()
invoices.loc[invoices['BillingCountry'] == 'Germany','Total'].sum()

156.48000000000002

In [26]:
## SELECT round(avg(Total),2) FROM Invoices WHERE BillingCountry = 'Germany';

invoices[invoices['BillingCountry'] == 'Germany']['Total'].mean().round(2)

5.59

In [27]:
# SELECT BillingCountry, round(sum(Total),2) monto, count(Total) cantidad, round(avg(Total),2) promedio 
# FROM Invoices 
# GROUP BY BillingCountry
# ORDER BY monto DESC;

invoices.groupby('BillingCountry')['Total'].agg(['sum','count', 'mean']).sort_values('sum', ascending=False)

                   sum  count      mean
BillingCountry
USA             523.06     91  5.747912
Canada          303.96     56  5.427857
France          195.10     35  5.574286
Brazil          190.10     35  5.431429
Germany         156.48     28  5.588571
United Kingdom  112.86     21  5.374286
Czech Republic   90.24     14  6.445714
Portugal         77.24     14  5.517143
India            75.26     13  5.789231
Chile            46.62      7  6.660000
Ireland          45.62      7  6.517143
Hungary          45.62      7  6.517143
Austria          42.62      7  6.088571
Finland          41.62      7  5.945714
Netherlands      40.62      7  5.802857
Norway           39.62      7  5.660000
Sweden           38.62      7  5.517143
Australia        37.62      7  5.374286
Denmark          37.62      7  5.374286
Italy            37.62      7  5.374286
Poland           37.62      7  5.374286
Argentina        37.62      7  5.374286
Belgium          37.62      7  5.374286
Spain            37.62      7  5.374286

In [28]:
# SELECT ar.Name, al.Title, t.Name 
# FROM artists ar 
# JOIN albums al ON ar.ArtistId = al.ArtistId
# JOIN tracks t ON t.AlbumId = al.AlbumId
# WHERE ar.Name = 'Pearl Jam' AND al.Title = 'Ten';

albums = pd.read_sql("SELECT * FROM albums", conn)
artists = pd.read_sql("SELECT * FROM artists", conn)
tracks = pd.read_sql("SELECT * FROM tracks", conn)

data = artists.merge(albums, on='ArtistId').merge(tracks, on='AlbumId')
data.loc[(data['Name_x']=='Pearl Jam') & (data['Title']=='Ten'),['Name_x', 'Title', 'Name_y']]

         Name_x Title    Name_y
2343  Pearl Jam   Ten      Once
2344  Pearl Jam   Ten  Evenflow
2345  Pearl Jam   Ten     Alive
2346  Pearl Jam   Ten    Why Go
2347  Pearl Jam   Ten     Black
2348  Pearl Jam   Ten    Jeremy
2349  Pearl Jam   Ten    Oceans
2350  Pearl Jam   Ten     Porch
2351  Pearl Jam   Ten    Garden
2352  Pearl Jam   Ten      Deep
2353  Pearl Jam   Ten   Release